FROM ghcr.io/hsm-sanosoft/hsm-base:latest

# Install the wkhtmltopdf CLI binary
RUN apt-get update \
  && apt-get install -y wkhtmltopdf \
  && rm -rf /var/lib/apt/lists/*

COPY package*.json .
RUN pnpm install
COPY . .
RUN pnpm build
CMD ["pnpm", "run", "start:prod"]